name: CI/CD Pipeline

on:
  pull_request:
    branches: [dev]
  push:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v3

      - name: Install backend dependencies
        run: cd backend && npm install

      - name: Run backend tests
        run: cd backend && npm test

      - name: Install frontend dependencies
        run: cd frontend && npm install

      - name: Run frontend tests
        run: cd frontend && npm test

      - name: Build Docker images
        run: docker compose build

  cd:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3

      - name: Install backend dependencies
        run: cd backend && npm install

      - name: Install frontend dependencies
        run: cd frontend && npm install

      - name: Login to DockerHub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build Docker images
        run: docker compose build

      - name: Push backend
        run: docker tag backend leopo361/ci-cd-app:backend && docker push leopo361/ci-cd-app:backend

      - name: Push frontend
        run: docker tag frontend leopo361/ci-cd-app:frontend && docker push leopo361/ci-cd-app:frontend

